name: Pre Check Plugin

on:
  pull_request:
    types: [opened, synchronize, ready_for_review, review_requested, edited]
    branches: 
      - main
      - dev
    paths-ignore:
      - ".github/**"
      - ".gitignore"
      - "unpacked_plugin/**"
      - "README.md"
      - "LICENSE"

env:
  REPO_NAME: langgenius/dify-plugins
  MARKETPLACE_BASE_URL: https://marketplace.dify.ai
  MARKETPLACE_TOKEN: placeholder
  GH_TOKEN: ${{ github.token }}

jobs:
  pre-check-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Clone Marketplace Toolkit
        run: |
          gh repo clone langgenius/dify-marketplace-toolkit -- .scripts/
      
      - name: Download Plugin Daemon
        run: |
          gh release download -R langgenius/dify-plugin-daemon --pattern "dify-plugin-linux-amd64" --dir .scripts
          chmod +x .scripts/dify-plugin-linux-amd64

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.7
      
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: yq - portable yaml processor
        uses: mikefarah/yq@v4.44.5
        with:
          cmd: yq --version

      - name: Get PR Path
        run: |
          export PR_FILES=$(gh pr view -R ${{ env.REPO_NAME }} ${{ github.event.pull_request.number }} --json files --jq .files)

          if PLUGIN_PATH=$(python3 .scripts/validator/check-pkg-paths.py); then
              echo $PLUGIN_PATH
              echo "PLUGIN_PATH=$PLUGIN_PATH" >> $GITHUB_ENV
          else
            echo "Only one .difypkg file change is allowed in a single PR."
            exit 1
          fi

      - name: Unpack File
        run: |
          mv ${{ env.PLUGIN_PATH }} ${{ env.PLUGIN_PATH }}.zip
          mkdir -p unpacked_plugin
          unzip ${{ env.PLUGIN_PATH }}.zip -d unpacked_plugin
          echo "PLUGIN_PATH=unpacked_plugin" >> $GITHUB_ENV

      - name: Check Plugin Manifest
        run: |
          # manifest.yaml author must not be langgenius or dify
          if yq '.author' ${{ env.PLUGIN_PATH }}/manifest.yaml | grep -q "langgenius"; then
            echo "!!! Plugin manifest.yaml author must not be 'langgenius'"
            exit 1
          fi
          if yq '.author' ${{ env.PLUGIN_PATH }}/manifest.yaml | grep -q "dify"; then
            echo "!!! Plugin manifest.yaml author must not be 'dify'"
            exit 1
          fi

      - name: Check Plugin Icon
        run: |
          # Get icon filename from manifest.yaml
          PLUGIN_ICON_FILENAME=$(yq '.icon' ${{ env.PLUGIN_PATH }}/manifest.yaml)
          echo "PLUGIN_ICON_FILENAME=$PLUGIN_ICON_FILENAME" >> $GITHUB_ENV
          
          # Check if icon file exists
          if [ ! -f "${{ env.PLUGIN_PATH }}/_assets/$PLUGIN_ICON_FILENAME" ]; then
            echo "!!! Plugin icon file not found: _assets/$PLUGIN_ICON_FILENAME"
            exit 1
          fi
          
          # Check if icon contains template placeholder text
          if grep -q "DIFY_MARKETPLACE_TEMPLATE_ICON_DO_NOT_USE" "${{ env.PLUGIN_PATH }}/_assets/$PLUGIN_ICON_FILENAME"; then
            echo "!!! Plugin icon contains template placeholder text 'DIFY_MARKETPLACE_TEMPLATE_ICON_DO_NOT_USE', change default icon before submitting to marketplace."
            exit 1
          fi
          
          # Define default icon content
          DEFAULT_ICON='<svg width="100" height="100" xmlns="http://www.w3.org/2000/svg">
            <path d="M20 20 V80 M20 20 H60 Q80 20 80 40 T60 60 H20" 
                  fill="none" 
                  stroke="black" 
                  stroke-width="5"/>
          </svg>'
          
          # Check if icon content matches default icon (normalize whitespace)
          ICON_CONTENT=$(cat "${{ env.PLUGIN_PATH }}/_assets/$PLUGIN_ICON_FILENAME" | tr -d '\n\r\t ' | tr -s ' ')
          DEFAULT_ICON_NORMALIZED=$(echo "$DEFAULT_ICON" | tr -d '\n\r\t ' | tr -s ' ')
          
          if [ "$ICON_CONTENT" = "$DEFAULT_ICON_NORMALIZED" ]; then
            echo "!!! Plugin icon is using the default template icon and must be customized"
            exit 1
          fi
  

      - name: Check If Version Exists
        run: |
          # Extract plugin metadata
          VERSION=$(yq '.version' ${{ env.PLUGIN_PATH }}/manifest.yaml)
          AUTHOR=$(yq '.author' ${{ env.PLUGIN_PATH }}/manifest.yaml)
          NAME=$(yq '.name' ${{ env.PLUGIN_PATH }}/manifest.yaml)
          
          echo "Plugin information:"
          echo "- Name: $NAME"
          echo "- Author: $AUTHOR"
          echo "- Version: $VERSION"
          
          # Check if the version already exists in marketplace
          echo "Checking if plugin version already exists in marketplace..."
          API_URL="${MARKETPLACE_BASE_URL}/api/v1/plugins/${AUTHOR}/${NAME}/${VERSION}"
          echo "API URL: $API_URL"
          
          RESPONSE_CODE=$(curl -s -o /dev/null -w "%{http_code}" "$API_URL")
          echo "API Response Code: $RESPONSE_CODE"
          
          if [ "$RESPONSE_CODE" = "200" ]; then
            RESPONSE=$(curl -s "$API_URL")
            if [ "$(echo "$RESPONSE" | jq -r '.code')" = "0" ]; then
              echo "!!! Plugin version $VERSION by $AUTHOR already exists in the marketplace."
              echo "!!! Please update the version number in manifest.yaml before submitting."
              exit 1
            fi
          else
            echo "Version check passed: $VERSION is available for use."
          fi

      - name: Check Plugin Deps
        run: |
          if [ -f "$PLUGIN_PATH/requirements.txt" ]; then
            echo "Trying to install plugin dependencies..."
            python3 -m venv .venv
            source .venv/bin/activate
            python3 -m pip install -r "$PLUGIN_PATH/requirements.txt"
            deactivate
          else
            echo "No requirements.txt found, skipping dependency installation"
          fi
      
      - name: Output Plugin Files Content
        run: |
          echo "::group::manifest.yaml"
          if [ -f "$PLUGIN_PATH/manifest.yaml" ]; then
            cat "$PLUGIN_PATH/manifest.yaml"
          else
            echo "manifest.yaml not found"
          fi
          echo "::endgroup::"
          
          echo "::group::README.md"
          if [ -f "$PLUGIN_PATH/README.md" ]; then
            cat "$PLUGIN_PATH/README.md"
          else
            echo "README.md not found"
          fi
          echo "::endgroup::"
          
          echo "::group::requirements.txt"
          if [ -f "$PLUGIN_PATH/requirements.txt" ]; then
            cat "$PLUGIN_PATH/requirements.txt"
          else
            echo "requirements.txt not found"
          fi
          echo "::endgroup::"

      - name: Check Plugin Install
        run: |
          if [ -f "$PLUGIN_PATH/requirements.txt" ]; then
              source .venv/bin/activate
              
              # Install packaging for version comparison
              pip install packaging
              
              # Determine installation method based on dify_plugin version
              echo "Detecting dify_plugin version..."
              dify_version=$(pip list | grep 'dify_plugin' | awk '{print $2}')
              target_version="0.0.1b64"
              
              echo "Found dify_plugin version: $dify_version"
              echo "Comparing with target version: $target_version"
              
              # Set environment variables based on version comparison
              if python -c "from packaging.version import Version; exit(0 if Version('$dify_version') > Version('$target_version') else 1)"; then
                  echo "Using serverless installation method"
                  export INSTALL_METHOD=serverless
                  export SERVERLESS_PORT=8080
                  export SERVERLESS_HOST=0.0.0.0
              else
                  echo "Using aws_lambda installation method"
                  export INSTALL_METHOD=aws_lambda
                  export AWS_LAMBDA_PORT=8080
                  export AWS_LAMBDA_HOST=0.0.0.0
              fi
              
              # Run the plugin installation test
              echo "Running plugin installation test..."
              python3 .scripts/validator/test-plugin-install.py -d "$PLUGIN_PATH"
          else
              echo "No requirements.txt found, skipping installation test"
          fi

      - name: Check Packaging
        run: |
          echo "Running packaging check..."
          python3 .scripts/uploader/upload-package.py -d "$PLUGIN_PATH" -t "$MARKETPLACE_TOKEN" --plugin-daemon-path .scripts/dify-plugin-linux-amd64 -u "$MARKETPLACE_BASE_URL" -f --test
